#version 430
#ifdef GL_ARB_shading_language_420pack
#extension GL_ARB_shading_language_420pack : require
#endif
#extension GL_ARB_compute_shader : require

layout(local_size_x = 1, local_size_y = 1, local_size_z = 1) in;

layout(binding = 0, std430) buffer _9_2
{
    int _m0[];
} _2;

layout(binding = 1, std430) buffer _9_3
{
    int _m0[];
} _3;

void main()
{
    _3._m0[int(gl_GlobalInvocationID.x)] = _2._m0[int(gl_GlobalInvocationID.x)];
}