#version 430
#ifdef GL_ARB_shading_language_420pack
#extension GL_ARB_shading_language_420pack : require
#endif
#extension GL_ARB_compute_shader : require

layout(local_size_x = 1, local_size_y = 1, local_size_z = 1) in;

layout(binding = 0, std430) buffer lay0
{
    int m_array[];
} inBuf;

layout(binding = 1, std430) buffer lay1
{
    int m_array[];
} outBuf;

void main()
{
    outBuf.m_array[int(gl_GlobalInvocationID.x)] = inBuf.m_array[int(gl_GlobalInvocationID.x)];
}